# Generated by Django 3.0.6 on 2020-05-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=500)),
                ('docs', models.FileField(upload_to='documents')),
                ('image', models.ImageField(null=True, upload_to='solution_images')),
                ('video', models.FileField(null=True, upload_to='videos')),
                ('soln_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('level', models.CharField(default='unsolved', max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('problemId', models.ForeignKey(db_column='problemId', on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
