# Generated by Django 3.0.6 on 2020-05-19 14:42

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('problemId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('RnD_Budget', models.CharField(max_length=20)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 20, 12, 18, 16162))),
                ('skill', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=105, size=5)),
                ('files', models.FileField(upload_to='file')),
                ('img', models.ImageField(upload_to='problem_images')),
                ('sol_count', models.IntegerField(default=0)),
            ],
        ),
    ]
